Link with libm for floor() function
LLD linker finds this missing symbol

arm-yoe-linux-gnueabi-ld.lld: error: undefined reference due to --no-allow-shlib-undefined: floor
>>> referenced by src/lib/libwsman.so.1.0.0

Signed-off-by: Khem Raj <raj.khem@gmail.com>